In [2]:
import pandas as pd
import numpy as np
pd.set_option('max_columns', 120)
pd.set_option('max_colwidth', 5000)


import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
plt.rcParams['figure.figsize'] = (12,8)

To ensure that code run fast for us, we need to reduce the size of lending_club_loans.csv by doing the following:

- Remove the first line: It contains extraneous text instead of the column titles. This text prevents the dataset from being parsed properly by the pandas library.
- Remove the ‘desc’ column: it contains a long text explanation for the loan.
- Remove the ‘url’ column: it contains a link to each on Lending Club which can only be accessed with an investor account.
- Removing all columns with more than 50% missing values: This allows us to move faster since don’t need to spend time trying to fill these values.

In [55]:
loans_2007 = pd.read_csv('data/lending_club_loans.csv', skiprows=1, low_memory=False)
loans_2007.shape

(42538, 115)

In [56]:
half_count = len(loans_2007)/2
loans_2007 = loans_2007.dropna(thresh=half_count, axis=1) # Drop any column with more than 50% missing values
loans_2007 = loans_2007.drop(['url','desc'], axis=1)
loans_2007.shape

(42538, 56)

In [57]:
loans_2007.head(3)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,fico_range_low,fico_range_high,inq_last_6mths,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,last_credit_pull_d,last_fico_range_high,last_fico_range_low,collections_12_mths_ex_med,policy_code,application_type,acc_now_delinq,chargeoff_within_12_mths,delinq_amnt,pub_rec_bankruptcies,tax_liens
0,1077501,1296599.0,5000.0,5000.0,4975.0,36 months,10.65%,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-2011,Fully Paid,n,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-1985,735.0,739.0,1.0,3.0,0.0,13648.0,83.7%,9.0,f,0.0,0.0,5863.155187,5833.84,5000.00,863.16,0.0,0.00,0.00,Jan-2015,171.62,Sep-2016,744.0,740.0,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
1,1077430,1314167.0,2500.0,2500.0,2500.0,60 months,15.27%,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-2011,Charged Off,n,car,bike,309xx,GA,1.00,0.0,Apr-1999,740.0,744.0,5.0,3.0,0.0,1687.0,9.4%,4.0,f,0.0,0.0,1008.710000,1008.71,456.46,435.17,0.0,117.08,1.11,Apr-2013,119.66,Sep-2016,499.0,0.0,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0
2,1077175,1313524.0,2400.0,2400.0,2400.0,36 months,15.96%,84.33,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,Dec-2011,Fully Paid,n,small_business,real estate business,606xx,IL,8.72,0.0,Nov-2001,735.0,739.0,2.0,2.0,0.0,2956.0,98.5%,10.0,f,0.0,0.0,3005.666844,3005.67,2400.00,605.67,0.0,0.00,0.00,Jun-2014,649.91,Sep-2016,719.0,715.0,0.0,1.0,INDIVIDUAL,0.0,0.0,0.0,0.0,0.0

In [58]:
data_dictionary = pd.read_csv('data/LCDataDictionary.csv')
data_dictionary = data_dictionary.rename(columns={'LoanStatNew': 'name',
                                                 'Description': 'description'})
data_dictionary.sample(10)

,name,description
59,num_accts_ever_120_pd,Number of accounts ever 120 or more days past due
14,delinq_amnt,The past-due amount owed for the accounts on which the borrower is now delinquent.
103,total_cu_tl,Number of finance trades
25,grade,LC assigned loan grade
33,installment,The monthly payment owed by the borrower if the loan originates.
97,tot_cur_bal,Total current balance of all accounts
50,mths_since_last_delinq,The number of months since the borrower's last delinquency.
92,sub_grade,LC assigned loan subgrade
37,last_fico_range_high,The upper boundary range the borrower’s last FICO pulled belongs to.
99,total_acc,The total number of credit lines currently in the borrower's credit file

In [59]:
loans_2007_dtypes = pd.DataFrame(loans_2007.dtypes, columns=['dtypes']).reset_index().rename(columns={'index':'name'})

loans_2007_dtypes['first_value'] = loans_2007.loc[0].values
preview = pd.merge(loans_2007_dtypes, data_dictionary, on='name', how='left')

In [60]:
preview.head()

,name,dtypes,first_value,description
0,id,object,1077501,A unique LC assigned ID for the loan listing.
1,member_id,float64,1.2966e+06,A unique LC assigned Id for the borrower member.
2,loan_amnt,float64,5000,"The listed amount of the loan applied for by the borrower. If at some point in time, the credit department reduces the loan amount, then it will be reflected in this value."
3,funded_amnt,float64,5000,The total amount committed to that loan at that point in time.
4,funded_amnt_inv,float64,4975,The total amount committed by investors for that loan at that point in time.

As you explore the features to better understand each of them, you’ll want to pay attention to any column that:

- leaks information from the future (after the loan has already been funded),
- don’t affect the borrower’s ability to pay back the loan (e.g. a randomly generated ID value by Lending Club),
- is formatted poorly,
- requires more data or a lot of preprocessing to turn into useful a feature, or
- contains redundant information.

In [61]:
preview[:19]

,name,dtypes,first_value,description
0,id,object,1077501,A unique LC assigned ID for the loan listing.
1,member_id,float64,1.2966e+06,A unique LC assigned Id for the borrower member.
2,loan_amnt,float64,5000,"The listed amount of the loan applied for by the borrower. If at some point in time, the credit department reduces the loan amount, then it will be reflected in this value."
3,funded_amnt,float64,5000,The total amount committed to that loan at that point in time.
4,funded_amnt_inv,float64,4975,The total amount committed by investors for that loan at that point in time.
5,term,object,36 months,The number of payments on the loan. Values are in months and can be either 36 or 60.
6,int_rate,object,10.65%,Interest Rate on the loan
7,installment,float64,162.87,The monthly payment owed by the borrower if the loan originates.
8,grade,object,B,LC assigned loan grade
9,sub_grade,object,B2,LC assigned loan subgrade
10,emp_title,object,NaN,The job title supplied by the Borrower when applying for the loan.*
11,emp_length,object,10+ years,Employment length in years. Possible values are between 0 and 10 where 0 means less than one year and 10 means ten or more years.
12,home_ownership,object,RENT,"The home ownership status provided by the borrower during registration. Our values are: RENT, OWN, MORTGAGE, OTHER."
13,annual_inc,float64,24000,The self-reported annual income provided by the borrower during registration.
14,verification_status,object,Verified,"Indicates if income was verified by LC, not verified, or if the income source was verified"
15,issue_d,object,Dec-2011,The month which the loan was funded
16,loan_status,object,Fully Paid,Current status of the loan
17,pymnt_plan,object,n,Indicates if a payment plan has been put in place for the loan
18,purpose,object,credit_card,A category provided by the borrower for the loan request.

In [62]:
drop_list = ['id','member_id','funded_amnt','funded_amnt_inv',
             'int_rate','sub_grade','emp_title','issue_d']
loans_2007 = loans_2007.drop(drop_list,axis=1)

In [63]:
preview[19:38]

,name,dtypes,first_value,description
19,title,object,Computer,The loan title provided by the borrower
20,zip_code,object,860xx,The first 3 numbers of the zip code provided by the borrower in the loan application.
21,addr_state,object,AZ,The state provided by the borrower in the loan application
22,dti,float64,27.65,"A ratio calculated using the borrower’s total monthly debt payments on the total debt obligations, excluding mortgage and the requested LC loan, divided by the borrower’s self-reported monthly income."
23,delinq_2yrs,float64,0,The number of 30+ days past-due incidences of delinquency in the borrower's credit file for the past 2 years
24,earliest_cr_line,object,Jan-1985,The month the borrower's earliest reported credit line was opened
25,fico_range_low,float64,735,The lower boundary range the borrower’s FICO at loan origination belongs to.
26,fico_range_high,float64,739,The upper boundary range the borrower’s FICO at loan origination belongs to.
27,inq_last_6mths,float64,1,The number of inquiries in past 6 months (excluding auto and mortgage inquiries)
28,open_acc,float64,3,The number of open credit lines in the borrower's credit file.
29,pub_rec,float64,0,Number of derogatory public records
30,revol_bal,float64,13648,Total credit revolving balance
31,revol_util,object,83.7%,"Revolving line utilization rate, or the amount of credit the borrower is using relative to all available revolving credit."
32,total_acc,float64,9,The total number of credit lines currently in the borrower's credit file
33,initial_list_status,object,f,"The initial listing status of the loan. Possible values are – W, F"
34,out_prncp,float64,0,Remaining outstanding principal for total amount funded
35,out_prncp_inv,float64,0,Remaining outstanding principal for portion of total amount funded by investors
36,total_pymnt,float64,5863.16,Payments received to date for total amount funded
37,total_pymnt_inv,float64,5833.84,Payments received to date for portion of total amount funded by investors

In [64]:
drop_cols = [ 'zip_code','out_prncp','out_prncp_inv',
             'total_pymnt','total_pymnt_inv']
loans_2007 = loans_2007.drop(drop_cols, axis=1)

In [65]:
preview[38:]

,name,dtypes,first_value,description
38,total_rec_prncp,float64,5000,Principal received to date
39,total_rec_int,float64,863.16,Interest received to date
40,total_rec_late_fee,float64,0,Late fees received to date
41,recoveries,float64,0,post charge off gross recovery
42,collection_recovery_fee,float64,0,post charge off collection fee
43,last_pymnt_d,object,Jan-2015,Last month payment was received
44,last_pymnt_amnt,float64,171.62,Last total payment amount received
45,last_credit_pull_d,object,Sep-2016,The most recent month LC pulled credit for this loan
46,last_fico_range_high,float64,744,The upper boundary range the borrower’s last FICO pulled belongs to.
47,last_fico_range_low,float64,740,The lower boundary range the borrower’s last FICO pulled belongs to.
48,collections_12_mths_ex_med,float64,0,Number of collections in 12 months excluding medical collections
49,policy_code,float64,1,publicly available policy_code=1\nnew products not publicly available policy_code=2
50,application_type,object,INDIVIDUAL,Indicates whether the loan is an individual application or a joint application with two co-borrowers
51,acc_now_delinq,float64,0,The number of accounts on which the borrower is now delinquent.
52,chargeoff_within_12_mths,float64,0,Number of charge-offs within 12 months
53,delinq_amnt,float64,0,The past-due amount owed for the accounts on which the borrower is now delinquent.
54,pub_rec_bankruptcies,float64,0,Number of public record bankruptcies
55,tax_liens,float64,0,Number of tax liens

In [66]:
drop_cols = ['total_rec_prncp','total_rec_int', 'total_rec_late_fee',
             'recoveries', 'collection_recovery_fee', 'last_pymnt_d',
             'last_pymnt_amnt']
loans_2007 = loans_2007.drop(drop_cols, axis=1)

In [ ]:
# Fico